POST http://localhost:39999/assignments
Content-Type: application/json

{
  "title": "string",
  "description": "string",
  "deadline": "2020-04-16 08:32:23"
}

###
GET http://localhost:39999/assignments/8d0cca56-eb9f-4f7d-a9b3-b037150f77e1/status

###
PUT http://localhost:39999/assignments/publish/8d0cca56-eb9f-4f7d-a9b3-b037150f77e1
