POST http://localhost:29999/submissions
Content-Type: application/json

{
  "code": "printf('hello world');",
  "assignment": "8d0cca56-eb9f-4f7d-a9b3-b037150f77e1"
}

###
GET http://localhost:29999/submissions
